### ISSUE TITLE
Unable to use QueryBuilder

### ISSUE THREAD

**Issue by rameshguthulakkd** [front/redisearch#1]
Hi 
I am using your code on my website's search. I want to use $prefixMathing on  FKRediSearch\Query\Query(). I am unable to use QueryBuilder on a string search Can you help me in this issue.
My exact problem is I need $prefixMatching with $tokenizer on a search  How is this possible. can you provide a small code example.

**Comment by Bjarzyna** [comment]
Hello,
what have you tried so far? You should be able to construct a query like this:
```
$query = new QueryBuilder();
$query->setTokenize()
  ->setPrefixMatching()
  ->addGenericCondition(["phrase 1", "phrase 2"], 'OR');
```
Make sure not to use `addGenericCondition`'s 3rd argument `$exact`, because it disables these search options for the condition group.
After that you can pass the instance of QueryBuilder to Query's `search()` method, which will automatically call the `buildRedisearchQuery()` method on that instance, stringifying it into a constructed RediSearch query.
Let me know if this doesn't work for you, ideally with some extra info about your environment and any errors / warnings that occur.
